### ISSUE TITLE
Mode: 0 Generator - dictionaries - passphrases 

### ISSUE THREAD

**Issue by phrutis** [phrutis/LostCoins#16]
We share our experience, regular expressions, links to dictionaries. 
We solve other issues related to passphrases here

**Comment by phrutis** [comment]
Dictionaries made on the generator do not need to be cleaned!

**Comment by phrutis** [comment]
If, after cleaning with the regular expression [^А-Яа-яA-Za-z0-9``~!@#$%^&*()-_=+[]{}|;:'"<>,./?\r\n]+, it still throws an error. 
Use [^\x1F-\x7F]+

**Comment by phrutis** [comment]
Dictionaries made on the generator do not need to be cleaned!
If, after cleaning with the regular expression [^А-Яа-яA-Za-z0-9``~!@#$%^&*()-_=+[]{}|;:'"<>,./?\r\n]+, it still throws an error. 
Use [^\x1F-\x7F]+
![7878](https://user-images.githubusercontent.com/82582647/132771305-7729678d-8d97-43ac-b057-f35cfdf1dde5.jpg)

**Comment by phrutis** [comment]
On large files, the total on the counter can be 5-7% more than the file's nominal - this is normal.

Do not use all processor cores, leave at least one for the system.

**Comment by Vladimir855** [comment]
(^ А-Яа-яA-Za-z0-9`` ~! @ # $% ^ & * () -_ = + [] {})   я бы не удалял т.к. эти символы могут быть в пароле от почты, а пароли по началу битка частенько вводились от почты. Были случаи находили по паролю о почты!!!!

**Comment by phrutis** [comment]
Как раз это выражение удаляет всё кракозябрики кроме символов внутри. Точнее находит и заменяет квадратики, иероглифы на ничто.
Это выражение [^\x1F-\x7F]+ удаляет все символы не входящие в ASCII диапазон

**Comment by phrutis** [comment]
Исходя из [таблицы ASCII](https://snipp.ru/handbk/table-ascii) выражение [^\x1F-\x7F]+ удаляет всё кроме английских букв, цифр, и символов. К сожалению русский буквы тоже удаляются, так как они находятся в другом диапазоне. 
Начало xBF -> xFF 
Вечером попробую задать два диапазона в выражении. Нужно тестить.

**Comment by agoora** [comment]
For MODE 0  and large address lists, why can't a separate bloom filter file be generated so that it can be used later, as brainflayer does?

**Comment by agoora** [comment]
And I think you can try xor filter, it's more faster.
https://github.com/FastFilter/xor_singleheader

**Comment by phrutis** [comment]
I do not know how the brainflayer does my windows. The filter can be faster, but for some reason the masters do not install it. But I can't do it

**Comment by phrutis** [comment]
**kpot87**
> в 0 режиме количество ключей с "-" это нормально?
Random mode : 0
Rotor : Loading private keys from file keys.txt ...
Loaded : -1142587849 private keys
Rotor : For large files use -t 11 max (1 core = ~30.000/s, 1 thread = ~5.000/s)
Site : https://github.com/phrutis/LostCoins
Donate : bc1qh2mvnf5fujg93mwl8pe688yucaw9sflmwsukz9

Нет, это не нормально! Предположительно в твоем файле более 1 000 000 000 строк. В описании я рекомендовал нарезать большие файлы по 500.000.000 строк макс. Ещё как вариант файл не очишен от мусора.

**Comment by agoora** [comment]
Hi phrutis,
Is it possible to add Ethereum to MODE 0 ?

**Comment by phrutis** [comment]
Lostcoins looks for hashes160 from all coins. Add hashes from Ethereum to the base.bin and search. 
If it finds Ethereum an empty address 1 and a positive hash160 and a private key. 
Convert positive hash160 to all coins

**Comment by phrutis** [comment]
### Mode 7

**Comment by agoora** [comment]
> Add hashes from Ethereum to the base.bin and search

How to convert from ETH to hash160?

**Comment by dextronomous** [comment]
hi there, great stuff, got one question is it possible to search for 1 address only. like from command prompt.? thanks again.

**Comment by phrutis** [comment]
dextronomous no, It could be done, no one needs it. Everyone wants to search for all coins, bases are already [15 gb](https://user-images.githubusercontent.com/50215875/133671106-2cc425b2-c993-4062-9c3e-18164592ffb3.png)
agoora the issue has been resolved long ago [here](https://github.com/phrutis/LostCoins/issues/19)

**Comment by dextronomous** [comment]
hi agian, not like that i meant your program is faast, looks great, soo  just one plain address like 1** something. in cmdline
thanks again for tip

**Comment by phrutis** [comment]
There will be more free time, we will make one address -a 1......., 3.....

**Comment by dextronomous** [comment]
oh wow super great. thanks again sir.

**Comment by agoora** [comment]
Hello everybody,

I also have a question:

What is the probability of finding a brainwallet with a positive balance, in 2021?
Has anyone here found one recently, so as not to waste our precious time?

Thank you in advance, for your experience sharing .

**Comment by phrutis** [comment]
### Mode 8
**Examples of parameters for generating passphrases in mode 8**
For test use: ```LostCoins.exe -b -t 6 -f test.bin -r 8 -n 3 -m 100 -d 5```

**With a large number of letters (words), there may be errors** 

Parameter **-t ?** How many cores, threads to use 1-127 Example -t 6 
Parameter **-n ?** number of generated letters 1-8 Example -n 5
U - ABCDEFGHIJKLMNOPQRSTUVWXYZ
l - abcdefghijklmnopqrstuvwxyz
D - 0123456789
Parameter **-m ?**

 -m 100 = abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 !#$%&'()*+,-./:;<=>?@[\]^_`{|}~
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 100 -d 5
Out: aW-3* -> #uP!$ -> WB^%0

LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 100 -d 5 -s Turbo
Out: TurboaW-3* ->Turbo#uP!$ -> TurboWB^%0

LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 100 -d 5 -s Turbo -z BOSS
Out: TurboaW-3*BOSS ->Turbo#uP!$BOSS -> TurboWB^%0BOSS

LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 100 -d 5 -z BOSS
Out: W-3*BOSS ->#uP!$BOSS -> WB^%0BOSS

 -m 101 = abcdefghijklmnopqrstuvwxyz
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 101 -d 5
Out: hello5 -> harek -> bober

LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 101 -d 5 -s Bitcoin
Out: Bitcoinhello5 -> Bitcoinharek -> Bitcoinbober

LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 101 -d 5 -s Bitcoin -z Day
Out: Bitcoinhello5Day -> BitcoinharekDay -> BitcoinboberDay

LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 101 -d 5 -z Day
Out: hello5Day -> harekDay -> boberDay


 -m 102 = ABCDEFGHIJKLMNOPQRSTUVWXYZ
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 102 -d 5
Same as in example 100-101 

 -m 103 = abcdefghijklmnopqrstuvwxyz0123456789
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 103 -d 5
Same as in example 100-101 

 -m 104 = ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 104 -d 5
Same as in example 100-101 

 -m 105 = ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 105 -d 5
Same as in example 100-101 

 -m 106 = ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 106 -d 5
Same as in example 100-101 

 -m 107 = 0123456789
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 107 -d 5
Same as in example 100-101 

 -m 108 = !#$%&'()*+,-./:;<=>?@[\]^_`{|}~
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 108 -d 5
Same as in example 100-101 

 -m 109 = 0123456789!#$%&'()*+,-./:;<=>?@[\]^_`{|}~
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 109 -d 5
Same as in example 100-101  


 -m 110 = ABCDEFGHIJKLMNOPQRSTUVWXYZ(SPACE)
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 8 -m 110 -d 5
Out: SUN DAY ->AAZZEEQQ -> FOR YOU(Space) -> ABC ABC W
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 8 -m 110 -d 5 -s SONY
Out: SONY SUN DAY ->SONYAAZZEEQQ -> SONY FOR YOU -> SONYABC ABC W
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 8 -m 110 -d 5 -s SONY -z Mega
Out: SONY SUN DAYMega ->SONYAAZZEEQQMega -> SONY FOR YOUMega -> SONYABC ABC WMega

 -m 111 = ABCDEFGHIJKLMNOPQRSTUVWXYZ(SPACE)
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 111 -d 5
Same as in example 110

 -m 112 = ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz(SPACE)
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 5 -m 112 -d 5
Same as in example 110


Tipo maska
 -m 113 = L<<-n 1-12 u>>DD
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 4 -m 113 -d 5
Out: Julia78 -> Alexx99 -> Fedor25

 -m 114 = L<<-n 1-12 u>>DDDD
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 4 -m 114 -d 5
Out: Julia1978 -> Alexx1999 -> Fedor2001

 -m 115 = Passphrase+L<<-n 1-12 u>>DD+Passphrase2
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 4 -m 115 -d 5
Out: Julia1978 -> Alexx1999 -> Fedor2001
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 4 -m 115 -d 5 -s XXX
Out: XXXJulia1978 -> XXXAlexx1999 -> XXXFedor2001
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 4 -m 115 -d 5 -s XXX -z WWW
Out: XXXJulia1978WWW -> XXXAlexx1999WWW -> XXXFedor2001WWW
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 4 -m 115 -d 5 -s XXX -z @google.com
Out: Julia1978@google.com-> Alexx1999@google.com -> Fedor2001@google.com

 -m 116 = Passphrase L<<-n 1-12 u>>DDDD Passphrase2
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 4 -m 116 -d 5
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 4 -m 116 -d 5 -s Passphrase
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 4 -m 116 -d 5 -s Passphrase -z Passphrase2
LostCoins.exe -b -t 6 -f test.bin -r 8 -n 4 -m 116 -d 5 -z Passphrase2

 -m 117 = L<<random 1-8 u>>random 1-4 D 
LostCoins.exe -b -t 6 -f test.bin -r 8 -m 117 -d 5
Out: Alex08 -> Masha1990 -> leon1

 -m 118 = Word+L<<random 1-8 u>>random 1-4 D+Word2 
LostCoins.exe -b -t 6 -f test.bin -r 8 -m 118 -d 5
Out: Alex08 -> Masha1990 -> leon1 -> Maximus1995
LostCoins.exe -b -t 6 -f test.bin -r 8 -m 118 -d 5 -s Good
Out: GoodAlex08 -> GoodMasha1990 ->Goodleon1 -> GoodMaximus1995
LostCoins.exe -b -t 6 -f test.bin -r 8 -m 118 -d 5 -s Good day -z Word 2
Out: Good dayAlex08Word 2 -> Good dayMasha1990Word 2 ->Good dayleon1Word 2 -> Good dayMaximus1995Word 2
LostCoins.exe -b -t 6 -f test.bin -r 8 -m 118 -d 5 -z Turbo max
Out: GoodAlex08Turbo max -> GoodMasha1990Turbo max ->Goodleon1Turbo max -> GoodMaximus1995Turbo max


 -m 119 = <<random 1-8 u>>(SPACE)<<random 1-8 u>>
LostCoins.exe -b -t 6 -f test.bin -r 8 -m 119 -d 5
Out: cool day -> good good -> generato wap

 -m 120 = <<random 1-8 u>>(SPACE)<<random 1-8 u>>(SPACE)<<random 1-8 u>>
LostCoins.exe -b -t 6 -f test.bin -r 8 -m 120 -d 5
Out:  abc abcdefgh passpass -> max perfect start

 -m 121 =  L<<random 1-8 u>>(SPACE)<<random 1-8 u>>
LostCoins.exe -b -t 6 -f test.bin -r 8 -m 121 -d 5
Out:  Bitcoin coins -> Alexandr man -> Burger kings ->Random full

If you are convinced that the setting is correct
Run fast mode **-d 3** without displaying letters.
You can add two, three words separated by a space to the -s or -z parameter

**Comment by agoora** [comment]
Please add base58 mode:

> -m 122      123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz

Thanks phrutis

**Comment by phrutis** [comment]
agoora ok

**Comment by agoora** [comment]
Thanks, I'm interested in the GPU version of this mode, when would it be ready?
Ex : Word+base58

**Comment by phrutis** [comment]
All possible addresses have long been checked against the addresses of the bases.
-m 122 ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789

**Comment by agoora** [comment]
This is correct base58 alphabet  "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"

**Comment by dextronomous** [comment]
hi thanks so much for such great piece, and please go go go, and 1 thing it not showing it is using -t 22 cpu's speed same.?

**Comment by phrutis** [comment]
I have CPU  i7 6 cores + 6 threads. 
Speed ~ 1 core = 30.000/s threads 3000/s
My max speed -t 6 160-180000/s or -t 12 180-200000/s 
Do you have 22 cores?

**Comment by dextronomous** [comment]
no it has 12 cores / 24 threads. but showing CPU: 1,91 Kk/s , with -t 1 or -t 22 or -t 11,

**Comment by phrutis** [comment]
Read carefully what is written below. 
>If you are convinced that the setting is correct
Run fast mode -d 3 without displaying letters.
You can add two, three words separated by a space to the -s or -z parameter

**Comment by dextronomous** [comment]
thanks again will it work btw with wallet.dat files.. > would be great..

**Comment by phrutis** [comment]
wallet.dat many fakes it is better to sort out passphrases or search by bit range

**Comment by dextronomous** [comment]
ok nice to know thanks a lot.. maybe my own wallet? anyway. but can you make it spit out sha256 phrases out of a list with addresses and use those as passwords with the -r .txt mode thanks again big brother..

**Comment by phrutis** [comment]
If your wallet try [core-decrypt](https://github.com/brichard19/core-decrypt)

**Comment by Evgen100707** [comment]
Will it be possible to run on OpenCL?

**Comment by phrutis** [comment]
Whom to launch? If you are looking for a private key, use the Rotor OpenCL. Core-decrypt work OpenCL. LostCoins work Cuda

**Comment by koteedj** [comment]
Привет) Подскажите с Генератором, хочу искать по 12 фразам. Сгенерировать есть такая возможность?

**Comment by phrutis** [comment]
12 фраз(слов) это мнемоник bip39 - это совсем другой алгоритм. Генератор не подойдет!
В LostCoins BIP39 хочу сделать в перспективе, пока не получается. 
На данный момент у [Noname400](https://github.com/Noname400) хорошая программа, и он развивает проект в этом направлении.

**Comment by phrutis** [comment]
**agoora**
I made a trial for one core -t 1. The code turns out to be very large. For all cores, I doubt that it will work correctly, a lot of redo.
Check out this correct conversion of private keys [here](https://brainwalletx.github.io) 
```
C:\Users\user>LostCoins2.exe -b -t 1 -f all.bin -r 0 -s 0.txt -d 1 -n 20

 LostCoins v3.3

 SEARCH MODE  : COMPRESSED & UNCOMPRESSED
 DEVICE       : CPU
 CPU THREAD   : 1
 GPU IDS      : 0
 GPU GRIDSIZE : -1x128
 RANDOM MODE  : 0
 ROTOR SPEED  : VERY SLOW (info+hashes+counter are displayed)
 CHARACTERS   : 20
 PASSPHRASE   : 0.txt
 PASSPHRASE 2 :
 DISPLAY MODE : 1
 TEXT COLOR   : 15
 GPU REKEY    : 100000000000
 HASH160 FILE : all.bin
 OUTPUT FILE  : Found.txt

 Loading      : 100 %
 Loaded       : 32,892,770 address

Bloom at 000001AA82A6CB70
  Version     : 2.1
  Entries     : 65785540
  Error       : 0,0000010000
  Bits        : 1891674723
  Bits/Elem   : 28,755175
  Bytes       : 236459341 (225 MB)
  Hash funcs  : 20

  Start Time  : Thu Sep 30 22:52:05 2021

  Random mode : 0
  Rotor       : Loading passphrases from file 0.txt ...
  Loaded      : 1464148 passphrases
  Rotor       : Only letters and symbols are supported: А-Яа-яA-Za-z0-9ёЁьЪЬъ `~!@#$&*()-_=+{}|;:'<>,./? others will be skipped!
  Rotor       : For large files use -t 11 max (1 core = ~30.000/s, 1 thread = ~5.000/s) Text file max 2,147,483,647 lines!
  Site        : https://github.com/phrutis/LostCoins
  Donate      : bc1qh2mvnf5fujg93mwl8pe688yucaw9sflmwsukz9


 [abc] [BA7816BF8F01CFEA414140DE5DAE2223B00361A396177A9CB410FF61F20015AD]
 [abc] [DFE7A23FEFEEA519E9BBFDD1A6BE94C4B2E4529DD6B7CBEA83F9959C2621B13C]
 [abc] [BBDB08DD3F8E0A2DBD9A4F45045FDF45CEBEE1AC6706DE3353E753234B318E78]
 [abc] [3C931CE976B2305A7393206E942F7A2222E2FB51649641FC44B8FF9429F48C]
 [abc] [FEAA749946B17883A4818551AB186C7E666A288C9CE188B8281BE45D298AC4F0]
 [abc] [981B79B75AF6F1403720CDB7A6E662FD68522923F913934C8507235BBDDD14D6]
 [abc] [14ACFC914BF07C2E300C2DACE0F2E7EAE48E3B991C56E3CA7179D5769DC99DBA]
 [abc] [40BC897703D98A915BCB49D05A0DB60D87027494C6FC0C0970ACBE206E855B19]
 [abc] [2EC633F07BA714FBD3D3DE0E5EF7BE9E453FA6B5847E2A85BD9C4A4C6CC5050B]
 [abc] [26378B5969F1B7FA4E73FE4D87CC8996E29BB1B2AD0E9A19CD207986664F7285]
 [abc] [4832AAF95D339B7FF1082CDEFDC62F071797F229134C63565E821BD73D9FC5F1]
 [abc] [FB8E1274AB3B675140DC77B968ADEBB143CF32DF92C4156A2A0BE95CD519CE1E]
 [abc] [8E4BA6E6D3900A424B26DCFAE97F938565EF129BECA0241F99FD0F4BCB3994F4]
 [abc] [467DCD6094702CFF70B2E1C451F0B5B21C7643A39172A03CDE72AA17954B3DDD]
 [abc] [93231F43E2D8F18AACEB5031099C3A53D49024559AEF507C03712E80B243A42]
 [abc] [DD16F27405078B1DB69B9D0C1E8C69258DB38C22B48EB9DD0FD08BF108199283]
 [abc] [91ACDF02FB5933EFC08D1833218AD0C1E6396B0ECC157B893D5233BF71C16442]
 [abc] [95796ECAB12CA1F19B8BD071F47258ED58A7D059D43F6E356293FC41A00AC731]
 [abc] [D3B013DA89535BC5C5E60EB55EAF89BA75BD77527AA7930F440A189884459F2E]
 [abc] [1D13B32B89BC4C7EE75FA5EAB7E4E1B9684CFFF46950CF9C813CDF78A17A1B1C]
 [fun] [C4285274FCC5D6FBA2EE58DAF0D8C2B9B825B68D35D65D0E90A9BB333A51B5]
 [fun] [6A40814E7636624ADDEE42DD8DD266162DAF97725F7545F02C55A1F6E39FF2A8]
 [fun] [D1F740C091A59D708F9F56F56A069A2CC2890E4728EBDAC044218AD9EE553D72]
 [fun] [1A6E9ED6C65EC620BDAC3AD22D753F815C30CFBCBB9CECCFE4DDCBB3A5AB4786]
 [fun] [49CED167AC3C7B5F1CF992B75067EEB0175B731614CF23E34D21E3DCC737476E]
 [fun] [7B82B6B980E181D8AED90CAE82FC3015CAF8C37ACB605224283AEEA551C24A29]
 [fun] [C05050F3797678D087019978007A30401EB810ED85985C48B2D1B1B158697619]
 [fun] [7D867B80612527B9358133FD378E7AC4AFEA2AA3BBB200EABE88CFDD4C3E28EF]
 [fun] [8F04F7E4B0BDB96F7DA3335DCEF18FBCC6B2EEF32C4A78332FD70F8B9F84F974]
 [fun] [96528885A378B27F2DE65820B2A9BC8EAFB5F01660A89BFAAD64EA61A40D6FE1]
 [fun] [99E45B1EF307E7C79E132C998E66C0C4DC40BAD0E00554A6760BEBEA7D377FDB]
 [fun] [6D30BA748205568BEA940D4993CD4FD9EC1D829D06AA693CC852BB6883E15BDF]
 [fun] [529781AFEF7ED267A89EF08096EBB1343ACA2CCB7B0F120D3D7E37000CC48475]
 [fun] [A42C6F857800AD6DFDA4FDB0A74C8191F37105DFA164C70EBD8C5FC0A6A98E9A]
 [fun] [FBDC823D1150DEBD39926BB6946069C4A428800ABA486C51585D0F72BF77DFB]
 [fun] [441EC82157820BA424369630FE07BE5A4A54BEF0101F62BC64561124E4777894]
 [fun] [EBB348C3A2C31AF8430043AEAD2743E151A27F712FE7280EFBB4B04B341124F0]
 [fun] [6A2C0183C984B397C88CBE31218421D022F455710016FA5909B8EA663D2272E3]
 [fun] [C62ECB692D34822A5F7655A9BDF21334AA98FE25B591D7B112A55415B16A0D78]
 [fun] [8A5BC440677888926D616411B8BA7804E7434C545B4C856A4BDE635E51C65C4]
```

**Comment by phrutis** [comment]
Start from abс. Private key should be with small letters. The program uses small letters, large letters are displayed in the print for clarity.

**Comment by agoora** [comment]
Hi phrutis,
Thansk, but you did not compile "LostCoins2.exe", where can I find it?

**Comment by phrutis** [comment]
LostCoins2.exe used for the test. I will add today at v3.3 
This add-on only works on one core! Maximum 256 conversions from sha256 to sha256 -t 1 -n 256

**Comment by agoora** [comment]
Ok tanks, can't run it on GPU?
Did you give up the mode, that I suggested: "word + base58"?

**Comment by phrutis** [comment]
The GPU is difficult, in the process of studying, possibly later.
word + base58 do it on the Generator.exe, there are many possibilities

**Comment by HasseM** [comment]
I was wondering what speeds people do get at mode0. I get about 2 Kk/s on a Xeon with 8 cores (-t 8).

**Comment by phrutis** [comment]
Very slow, try add **-e** You haw ssd disk?
>Do not use all processor cores, leave at least one for the system.

**Comment by HasseM** [comment]
Did you ever encounter a situation where your release build fails the checkPrivKey function? My debug build runs fine, but my release build fails at every key in the checkPrivKey function. More specific, the checkAddress function finds a valid key in all the Endomorphism blocks (checkBloomBinary returns true). I noticed the pte1[] and pte2[] arrays being zero, causing a h0 to be different.

I have no clue why this is happening at all. It only happens in release build. I compared project settings and they are the same. So it must be in the code. I have modified the code by a lott, I do not see it on your build. I am hoping you have seen something like this during development?

**Comment by phrutis** [comment]
There it was originally. I did it my own way, shortened the code, muffled the speed so that values were not added to each private key. Perhaps programmers do not do that, they did it to the best of their knowledge. The main thing is it works.
As for Endomorphism and others, these functions are inherited from VanitySearch they are not used in LostCoins as the code was changed and partially removed.
If you need the source code of the functions see VsnitySearch
