### ISSUE TITLE
Error found and request for some help / explaination

### ISSUE THREAD

**Issue by HasseM** [phrutis/LostCoins#22]
I noticed that there is a crash when using t=0 as parameter. It crashes on line 188 in LostCoins.cpp (this->nbit = n / nbit2;) because nbit2 = 0. nbit2 is also initialized as zero. So input parameters should be checked a bit better and when not specifying a valid value of nbit2 should be considered.

The reason why I ran into this problem is probably because of a bit unclear explanation of the parameters. It's clear not to use both cpu and gpu, hence I used t=0... also the different modes are really unclear yet to me.

Any advice on using an RTX3090 gpu with a external passwords.txt file?

What gridsize to specify would require some explaination to, I guess...

**Comment by phrutis** [comment]
Use example modes. No need to experiment and set incomprehensible parameters, it will give an error.
Take screenshots of errors, get an answer. You cannot divide by zero. You have started a process with 0 cores

**Comment by HasseM** [comment]
Well, the default command line options in project settings (debug config) are:
-t 0 -g -i 0 -x 256,256 -n 256 -f address1-160-sorted.bin

This one also crashes because of -t 0.

**Comment by phrutis** [comment]
Mode 0 has no GPU support.

**Comment by agoora** [comment]
I'm also interested in the GPU version, of mode 0, to check a txt file with passwords!
Do you think that you can implement it and that it significantly increases the speed, compared to the CPU?

**Comment by phrutis** [comment]
Do you want to split a text file of 10.000.000 lines into 65535 threads and check it at a speed of 2500000000 / sec?
Have you ever tried riding a motorcycle around your apartment?
I don’t understand why this is necessary? The processor speed is fast enough to check a small file up to 500,000,000 lines. Large files can cause errors.
