### ISSUE TITLE
Sha256 from random 

### ISSUE THREAD

**Issue by Menline79** [phrutis/LostCoins#31]
Есть ли возможность в режиме random генерировать случайное число с определенным количеством бит (120 например), а потом выполнять Sha256 этого числа и проверять полученный ключ.
Возможно есть такая функция? Или подскажите где в программе добавить код.

**Comment by phrutis** [comment]
Если знаешь C++ в LostCoins.cpp
В коде можно добавить так:
для CPU:
Int mme.Rand(120);
string nos = sha256(&mme);								char* cstr = &nos[0];								key.SetBase16(cstr);

Для GPU:
Int mme.Rand(120);
string nos = sha256(&mme);								char* cstr = &nos[0];								keys[i].SetBase16(cstr);

Если немного нужно можешь прогнать в режиме 0
Можно так: на генерировать privat keys 120 bit в файл.
Запуск ```LostCoins.exe -b -t 1 -f test.bin -r 0 -s Privat-keys120.txt -d 1 -n 1``` работает только на одном ядре -t 1 Сколько раз преобразовать в sha256 в твоём случае используй -n 1 (-n 100 это сто раз преобразовать в sha256) если ищешь только сжатые убери -b

**Comment by Menline79** [comment]
Добрый день!
Подскажите, где именно в коде вставить эти строки. Я не силен в  C ++
