### ISSUE TITLE
Добавить возможность подбора по WIF (его части)

### ISSUE THREAD

**Issue by Karvanish** [phrutis/LostCoins#32]
Всем доброго времени! 
Прошу добавить функцию перебора/рандома WIF приваткеев используя их части. Допустим у меня есть адрес и привкей к нему, но в привкее спереди потеряно 9 символов (5J?????????XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX)

Скрипт должен генерировать последовательную и рандомную потерянную часть WIF, после чего конвертировать WIF в адрес/ripe160/pubkey и сравнивать его с эталонным.

Добавлю, что возможность необходима как для uncompressed так и compressed WIF/адресов.

**Comment by phrutis** [comment]
Сейчас думаю как это реализовать? 
Модернизировать 3-й режим сложно, 7-й переделывать накладно.
Попробую сделать 8-й режим. Вопрос только приваты гнать только из 5-ки ?

**Comment by Karvanish** [comment]
Конкретно для моего кейса - да, из 5ки (51 символ), но я думаю, что у людей будет много запросов на compressed приваты (52 символа на K,L)

**Comment by phrutis** [comment]
>Скрипт должен генерировать последовательную и рандомную потерянную часть WIF, после чего конвертировать WIF в адрес/ripe160/pubkey и сравнивать его с эталонным.

Последовательно не получится, только рандом.

WIF -> в адрес (не правильно).
WIF -> Privat key -> дальше по алгоритму...

>Добавлю, что возможность необходима как для uncompressed так и compressed WIF/адресов.

Это по желанию указывай. 
Если ничего не указывать или -c ищет только сжатые. 
-u не сжатые.
-b сжаты + не сжатые 

Делаю для L, K, 5 тестирую...

**Comment by phrutis** [comment]
Поиск по WIF сложный, требует навыков.
Нужно задать правильные параметры генерации!
Если задать меньше или больше на один два символа -> может не работать, может выдавать смещенный private keys и т.п.
В ходе моих тестов было выявлено, для не сжаты 5... не все WIF подходят. 
Версию 5.5 пока не буду добавлять, тестируйте... 
Программу можно скачать [**ЗДЕСЬ**](https://github.com/phrutis/LostCoins/blob/main/Others/WIF.exe) (для тестов)
Проверять можно [**ЗДЕСЬ**](https://secretscan.org/PrivateKeyWif), нужно подобрать правильные настройки что бы WIF соответствовал HEX и на оборот.

Пример запуска теста:
Показывает сколько символов + WIF
```WIF.exe -t 1 -f test.bin -r 8 -s Kxxxxxxxxxxx -n 10 -z TTTTTTTTTT -m 20 -d 0```

Показывает WIF и Private key
```WIF.exe -t 1 -f test.bin -r 8 -s Kxxxxxxxxxxx -n 10 -z TTTTTTTTTT -m 20 -d 1```

Быстрый режим
```WIF.exe -t 1 -f test.bin -r 8 -s Kxxxxxxxxxxx -n 10 -z TTTTTTTTTT -m 20 -d 3```

Пример
![001](https://user-images.githubusercontent.com/82582647/142780629-19c42d0a-e387-4c7c-afba-2f9998b2d566.jpg)

Пример
![567](https://user-images.githubusercontent.com/82582647/142780653-2e026185-e947-44f4-b45b-8e1ff9711363.jpg)

**Comment by phrutis** [comment]
Два дня прошло тишина, отпишись по тестам.

**Comment by Karvanish** [comment]
Работает хорошо, но скорость, конечно, низкая. Как добиться хотя бы такой же скорости как в софте FinderOuter? Там у меня выходит ~25 млн/сек, тут ~430 тыс/сек.

**Comment by phrutis** [comment]
Могу включить скалярное умножение векторов скорость будет ~x50-x100 
С таким же успехом можно сделать на GPU.
скорость будет ×1000
Сейчас медленно но правильно.

**Comment by Karvanish** [comment]
Вот на GPU было бы самое то, хоть какие то минимальные шансы :)

**Comment by Ak535Ak** [comment]
> Два дня прошло тишина, отпишись по тестам.

Мне не зашло, толи руки кривые толи рандом, как не настраивал параметры, генерирует не валидные WIF, по bitaddress.org не бьются. Задумка хорошая, ждем новых обновлений.

**Comment by phrutis** [comment]
Ak535Ak здесь как я понял нужны знания, и прямые руки  это сложный способ.
Задавать параметры генерации нужно с умом. Нужно знать кие части(хвосты) крутить, а какие должны быть константными.
Если задавать от лампочки(по красоте) буду частично рандомится не верные WIF, которые могут вообще не соответствовать никакому приват кею. 
В этом случае прога может выдавать смещенные или левые приват кеи.

Karvanish сделай 3 ссылки с параметрами для наглядного примера, для 5,L,K.

**Comment by phrutis** [comment]
Как это ещё zh76internetru здесь нет )))
Он мастер хвосты крутить )))

**Comment by Smsu838** [comment]
https://learnmeabitcoin.com/technical/wif виф это не просто же рандом ))

**Comment by Ak535Ak** [comment]
Так расчет то и был на то что программа будет генерировать в правильном порядке с правильным checksum, а так можно любой Crunch заставить 52 цифры рандомно гонять.

**Comment by Smsu838** [comment]
Ну типа да

**Comment by phrutis** [comment]
Ak535Ak Расчет был что частично уже известен wif, были не известны определённые символы.
К примеру в нете где-то кто-то, засветил часть WIF.
Или намеренно сделал головоломку где есть неизвестные части. Где-то давно я видел wif с замазаными частями много.
В этом случае есть смысл порандомить.

**Comment by Ak535Ak** [comment]
> Ak535Ak Расчет был что частично уже известен wif, были не известны определённые символы. К примеру в нете где-то кто-то, засветил часть WIF. Или намеренно сделал головоломку где есть неизвестные части. Где-то давно я видел wif с замазаными частями много. В этом случае есть смысл порандомить.

Согласен, таких было много в разных постах, я и говорю что задумка интересная, ее бы допилить до ума.
Я и подумал что раз он может рандомить часть известного Wifа то почему бы не взять например первый от 64го пазла KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qYvLz3frbdQx38qLdPR8 и попробовать по рандомить до 
KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qZ71LwzbM1Mo2Q65MWiS, таким путем ./WIF.exe -t 1 -f new.bin -r 8 -s KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3q -z -m 19 -d 0
но увы не один wif не бился с существующим и разносился по разным диапазонам.

**Comment by phrutis** [comment]
WIF.exe -t 1 -f new.bin -r 8 -s KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3q -m 19 -d 0
 Возможно так будет работать некорректно.
Попробуй так
WIF.exe -t 1 -f new.bin -r 8 -s KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3q -n 10 -z x -m 8  -d 0

**Comment by phrutis** [comment]
Параметр -m обязательный если его не использовать по умолчанию -m 100

**Comment by Ak535Ak** [comment]
Попробую отпишусь

**Comment by phrutis** [comment]
Протестировал, всё работает отлично.
Качаем [test.bin](https://github.com/phrutis/LostCoins/releases/download/5.0/test.bin) в нем есть адрес с WIF: 5JiznUZskJpwodP3SR85vx5JKeopA3QpTK63BuziW8RmGGyJg81

Запуск короткого теста, поиск не сжатого WIF:
 ```WIF.exe -b -t 1 -f test.bin -r 8 -s 5JiznUZskJpwodP3SR8 -n 3 -z 5JKeopA3QpTK63BuziW8RmGGy -m 4 -d 3```

Результат:
![5J](https://user-images.githubusercontent.com/82582647/143080211-71706c2f-efa5-4c9d-bfaa-e4cb8e1f2180.jpg)
---
Запуск короткого теста, поиск сжатого WIF: L3UBXym7JYcMX91ssLgZzS2MvxTxjU3VRf9S4jJWXVFdDi4NsLcm
```WIF.exe -b -t 1 -f test.bin -r 8 -s L3UBXym7JYcMX91ssLgZ -n 3 -z MvxTxjU3VRf9S4jJWXVFdDi4N -m 4 -d 3```

Результат:
![K](https://user-images.githubusercontent.com/82582647/143081774-1d4c0c1f-ff18-4fc8-8d58-91b5838f0ee5.jpg)

**Comment by phrutis** [comment]
Тесты закончились, файл WIF.exe удалил. 
Кто не успел смотрите 8-й режим в LostCoins

**Comment by Smsu838** [comment]
В 8-ом режиме похерился поиск -c только -b или так задумано?

**Comment by phrutis** [comment]
-с никогда не использовал, тогда без ничего будет поиск сжатых (ссылку поправил спс)
-u Искать не сжатые
-b Искать оба варианта

**Comment by dextronomous** [comment]
(51) [KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qZFYxAQwuRfgAqryP38] [34F72C234F72C234F72C234F72C234F72C234F72C234F72C29230EB98B955031] 00 Mk/s] [T: 60,560] [F: 0] what is this second line 
should the hex private key not be 16 characters the missing wif 17 from the compressed one? please explain and a little help would be appreciated with this one. thanks a lot again phrutis,

**Comment by phrutis** [comment]
The first line is WIF private key, the second is HEX private key. Convert WIF to HEX -> [PrivateKeyWif](https://secretscan.org/PrivateKeyWif)

-m 1-20 required parameter (-m 0 this is not allowed)
Try: -s KwDiBf89QgGbjEhKnhXJuH7LrciVrZi3qZ -n 10 -m 7 -d 1
