### ISSUE TITLE
what is this error ?

### ISSUE THREAD

**Issue by studyroom1** [phrutis/LostCoins#35]
ModMulK1order() Wrong !

**Comment by phrutis** [comment]
Take a screenshot of the error

**Comment by studyroom1** [comment]
> Take a screenshot of the error
![image](https://user-images.githubusercontent.com/44286184/146037487-827de620-b412-4727-b617-4b2f0000a43f.png)

**Comment by phrutis** [comment]
Do not pay attention! This check is inherited from VanitySearch. 
The code has been changed and modified, so this check does not work properly
