### ISSUE TITLE
Напиши подробнее какой файл открыл, как открыл, куда хочешь попасть, для чего и т.п.?

### ISSUE THREAD

**Issue by rsssss01** [phrutis/LostCoins#36]
Ну смотри) Я так понял, у тебя готовая прога, по подбору seed фраз для кошельков.
Она же наверное автоматизирована, а за мной нужен только маниторинг. Так я не могу ее запустить)) Может я ошибся и это только очень сильно разжеванный "мануал" 
и нужно прописывать самостоятельно какие либо коды и дорабатывать самостоятельно. Если это так, помоги разобраться, а я в долгу не останусь)
P.S Я видел у тебя кошелек для пожертвований))

**Comment by phrutis** [comment]
Умеешь пользоваться командной строкой?

**Comment by phrutis** [comment]
1.Рядом с программой LostCoins.exe положи файл test.bin, и создай текстовый файл.
2.Напиши в файле:
:loop 
LostCoins.exe -t 6 -f test.bin -r 4 -s 252 -z 256 
goto :loop 
Сохрани.
3.Переименуй файл Текстовый файл.txt в **Start.bat** сохрани. 
Щелкни 2 раза правой кнопкой мыши по файлу Start.bat программа запустится. 

Для других режимов: 
открой Start.bat текстовым редактором. 
Меняй строку запуска, параметры и значения. 
Так же посмотри как создать базу bin [здесь](https://github.com/phrutis/Rotor/issues/1)
Не торопись, изучи, что куда, перечитай темы Русские кладоискатели.

**Comment by rsssss01** [comment]
Хорошо, спасибо огромное.Очень странно правда, в наше время люди не ленятся помогать незнакомцам. Ты хороший человек)
И еще, если будут вопросы я могу обращаться?

**Comment by phrutis** [comment]
В следующий раз старайся описать подробнее свою проблему, вопрос, предложение, идею и т.п.
Если будут вопросы по работе программы делай скриншот окна. Не обязательно создавать вопрос в вопроснике, есть активная тема Русские кладоискатели пиши там.

**Comment by rsssss01** [comment]
Cлушай, сделал все как сказал. Програму нашел LostCoins в папке Release. Правда без .exe , но все вроде получилось, правда нужна какая то прога через которую можно запустить Test.bin потому что он мне дает возможность запустить прогу через Torent Я сам не понял почему так, а без этого она не открывается, теперь больше не понимаю чем до этого

**Comment by rsssss01** [comment]
![image](https://user-images.githubusercontent.com/96095728/145957729-c1272449-6035-4a8f-8ba5-c2ff66ca04b9.png)

**Comment by rsssss01** [comment]
![image](https://user-images.githubusercontent.com/96095728/145957900-b1ede974-2418-47cf-8b62-aeb464508329.png)
Вот еще возможности

**Comment by phrutis** [comment]
test.bin - это бинарная база адресов. 
Его ничем не открыть и не нужно этого делать.
Судя по скрину, ты сделал не правильно!

У тебя другая проблема, у тебя скрыты зарегистрированные расширения файлов.
Как включить смотри [здесь](https://zen.yandex.ru/media/tehnichka/kak-pokazyvat-rasshireniia-failov-v-windows-10-5fe4452babcef566156da782?utm_source=serp)
Как снимешь галку, нажми применить.
Посмотри на Start.bat )))

**Comment by phrutis** [comment]
Если всё сделаешь правильно будет выглядить так:
LostCoins.exe
test.bin
Start.bat.txt

В Start.bat~~.txt~~ удали .txt получится **Start.bat**
Вот его и запускай

**Comment by rsssss01** [comment]
![image](https://user-images.githubusercontent.com/96095728/145965512-32335da1-63e5-44bf-a123-4df7f4ff2620.png)

**Comment by rsssss01** [comment]
Во) Только, где кошельки)))

**Comment by phrutis** [comment]
Сколько ядер проц? Видюха как называется?

**Comment by rsssss01** [comment]
Вообщем, я запустил прогу, а куда инфа падает о том, что seed фразы подобраны верно или же не верно? Или может я совсем ничего понимаю? Теперь просто ждать какого либо результата? Если же он даже и будет то где его посмотреть?

**Comment by rsssss01** [comment]
И что означает Строка Donate? Я могу предположить что это кошелек куда приходит битки, которые на "майнились" за все время?

**Comment by rsssss01** [comment]
2 ядра, nvidia geforce gts 450

**Comment by phrutis** [comment]
>Или может я совсем ничего понимаю?

Видимо да )))

>Теперь просто ждать какого либо результата?

256 бит на CPU - это более 10000000000000000000000000000000 лет ждать )))

Donate это мой кошелёк :)
Если найдёшь клад, можешь поделится.

Программа ищет ключи от кошельков из базы.
Если найдёт появится сообщение какой адрес был подобран, + ключи от него и т.п. + запишет это в файл Found.txt

У тебя слабый комп, используй вместо -t 6, -t 2
С твоей скоростью ищи 64-й пазл на [Rotor-Cuda](https://github.com/phrutis/Rotor-Cuda).
Скачай Rotor-Cuda.exe
Поменяй строку LoatCoins.... на эту:
```
Rotor-Cuda.exe -t 2 -m address --coin BTC -r 1 --range 8000000000000000:ffffffffffffffff 16jY7qLJnxb7CHZyqBP8qca9d51gAjyXQN
```
Это самый оптимальный вариант.

**Comment by rsssss01** [comment]
Хорошо, я поделюсь) 
В принципе понял, приедет друг программист хороший знающий язык, настроит .
Ты только объясни пожалуйста как понять кошелек, и где это сделать. И объясни пожалуйста, куда после загрузки мне нужно поместить Rotor-Cuda?)))
И еще я надеюсь, я тебе не надоел еще)

**Comment by phrutis** [comment]
Куда угодно. Главное что бы был рядом с программой был файл Start.bat и база.bin
Что бы пройти весь 64-й диапазон на двух ядрах тебе понадобится всего ~6000 лет. С рандомом шанс найти будет быстрее. Поставь на поиск пазла и изучай что куда... Удачи

**Comment by rsssss01** [comment]
Cпасибо)
Счастливо друг)
