### ISSUE TITLE
Privat keys from a file. Only the first key.

### ISSUE THREAD

**Issue by Igor-cherkassy** [phrutis/LostCoins#37]
finds only the first private key in the list! 1+n keys Ignored. Please correct the error.

**Comment by phrutis** [comment]
Сделай скриншот. 
Или напиши строку которой запускаешь

**Comment by phrutis** [comment]
Не дождусь от тебя скрина
Мои тесты, стандартный test.bin 
Проверка private keys из файла с маячками 4 шт. (1 начале, 2 в середине и 1 в конце списка)

![436](https://user-images.githubusercontent.com/82582647/146215726-bfba4ffa-8757-4a92-b46a-ff4151ee20ca.jpg)

![437](https://user-images.githubusercontent.com/82582647/146215812-d4ccea41-5674-4ff1-98f7-7df0c08a20f0.jpg)

# Тест 2
Молотим приват кеи из списка private-key.txt 
Каждый приват кей в списке преобразовывается 20 раз в sha256 (установлено -n 20)
После каждого преобразования из полученного приват кея генерируется адрес который проверяется по базе.  

Private key 4a70fe9aa6436e02c2dea340fbd1e352e4ef2d8ce6ca52ad25d4b95471fc8bf2 -> sha256 x 10 раз =
9b1c1044ec74b7ae7623ef1edd62b9650cf473336fa28e49f944de52e6424155 
соответствующий адресу 1dPGPV1hc1AmkiHgdNXk8cGkicogRxfKA

![6555](https://user-images.githubusercontent.com/82582647/146219628-a47dc3dc-d8f8-47d9-8114-0ea9244e0cb7.jpg)

**Comment by Igor-cherkassy** [comment]
1.Танцы с бубном помогли. Но все равно последний адрес в списке с заведомо правильным ключём не находит ( из 10 миллионов).
 2.Пробовал видеокарту, после 1 -2 сек закрывает программу, жаль нет поддержки. 
3. К сожалению 1 000 000 000 ключей это очень мало.
4. Спасибо вам за быструю поддержку проекта!

**Comment by phrutis** [comment]
Недавно объяснял почему -t 1 пропадает последние 2 строки.
Если использовать более чем -t 1 последние строки не пропадут

>Это технический момент последняя строка пропускается.
For считает от 0 по этому на 1 будет меньше.
От суммы сделал что бы отнимало последнюю строку (слово) -1
Вот и получается что будет показывать количество на 2 фразы меньше.
Это сделано для остановки поиска.
Долго объяснять.
Попробую на примере. Если не отнимать -1.
Будет 10. Когда поток будет обрабатывая строки и дойдёт до 10-й строки, он начнёт снова поиск с 0 до 10-ти. и так по кругу.
Как его остановить?
Самый простой способ
if (строка => 9) { стоп }
Если строка равняется или больше 9 остановка.
Если if (строка => 10) { стоп }
Здесь утка не сработает, равно на больших скоростях и много поточности не успеет и поиск начнётся с начала и так по кругу. Пробовал по разному, это тот минимум при котором срабатывает остановка.
К тому же очень часто последняя строка пустая.
В итоге теряется последняя строка, иногда может потерятся предпоследняя.

>При делении на 11 потоков может потеряться 10 последних строк если к примеру количество будет 1110. При многопоточности на больших файлах есть погрешность +5-7% к тоталу.
Первый поток запускается сразу, 11-й на большом файле 2,100,000,000 может спустя 10 мин.
Процесс закончится когда 11-й поток пройдёт свою часть диапазона. Так как первый, второй уже прошли свой диапазон, начинаю перебирать следующий по возрастанию. Потоки 1,2,3 нельзя остановить так как 10,11 ещё не прошли свою дистанцию. Получается что первый поток перелазит в диапазон второго и начинает его в ожидании когда 11-й пройдёт свою часть и остановит программу. Перелезая потоки проходят потерянные строки при делении (если такие были) По этому тотал может быть +5-7%

**Comment by phrutis** [comment]
>1 000 000 000 ключей это очень мало

Максимум  2 147 000 000 строк ограниченно int доступным диапазоном.
Можно сделать unsigned long long 18 446 744 073 709 551 615 строк, с таким файлом будут другие проблемы!
Если ядер много (64-128) запускай копии программы с -t 11 и другими текстовыми файлами - это тот максимум что можно выжать.
Что касается GPU, я ели добился 11 (-t 11) пытался сделать 12 ошибка! Всё перепробовал.
Для понимания у GPU 65536 потоков, не представляю как это может работать?!

**Comment by Igor-cherkassy** [comment]
Спасибо. 
Как остановить программу не закрывая окно? ctrl C не работает
