### ISSUE TITLE
Не пишет в LostCoins-Continue.bat

### ISSUE THREAD

**Issue by agrusan** [phrutis/LostCoins#39]
Привет. Попробовал режим 1, создал файл LostCoins-Continue.bat.  Запускаю, в него ничего не пишет не через 5 минут не через час

**Comment by phrutis** [comment]
Напиши строку которой запускал.
Напиши содержание бат файла, или сделай скрин.
Продолжение работает только для GPU.
Пример запуска: ```LostCoins.exe -t 0 -g -i 0 -x 256,256 -f test.bin -r 1 -s ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff0000000000 -z ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ffffffffffff -d 4 -n 5```
Через 5 минут появится бат файл продолжения.
Далее через каждые ~5 минут информация в файле будет обновлятся.
К примеру через час мы остановили программу.
Через два часа решили продолжить. Нажимаем на файл продолжения. Программа запустится с того места где была остановлена. +-5 минут.

Если решили запустить другой диапазон и т.п. Нужно удалить (можно переименовать LostCoins-Continue.bat к примеру в LostCoins-Continue555.bat) так как при старте другого(нового) диапазона счетчик возьмётся из бат файла и вместо старта будет некорректное продолжение.
