### ISSUE TITLE
Mode 8

### ISSUE THREAD

**Issue by teddy3130** [phrutis/LostCoins#40]
Any future plans to add GPU for mode 8

**Comment by phrutis** [comment]
This is implemented in a separate project [Fialka M-125](https://github.com/phrutis/Fialka)

**Comment by teddy3130** [comment]
Thank you phrutis

**Comment by mzciry** [comment]
> Any future plans to add GPU for mode 8

Contact me on telegram I have a solution and an offer @mzciry
