### ISSUE TITLE
Вопрос про рандом!

### ISSUE THREAD

**Issue by vinceonline** [phrutis/LostCoins#43]
Приветствую, скажите каким образом значение -r можно уменьшить?? Как мне добиться эффекта рандома в 1 единицу, то есть каждый приватный ключ будет вообще радомным!!

**Comment by phrutis** [comment]
Режим 7 - Полный рандом. 
Каждый приват кей разный.
В этом режиме не используется быстрое скалярное умножение векторов, по этому скорость низкая.

**Comment by vinceonline** [comment]
> Режим 7 - Полный рандом. Каждый приват кей разный. В этом режиме не используется быстрое скалярное умножение векторов, по этому скорость низкая.

а в чем проблема сделать такой же режим через GPU???

**Comment by phrutis** [comment]
LostCoins, Rotor-Cuda работают на CUDA там сложно это реализовать.
К тому же есть [Rotor](https://github.com/phrutis/Rotor) на OpenCL 3-я версия молотит в режиме полный рандом.
Есть нюансы читай внимательно маин.
