### ISSUE TITLE
amd gpu's support

### ISSUE THREAD

**Issue by DapTice** [phrutis/LostCoins#45]
Поддержку АМД видеокарт завезут?

**Comment by phrutis** [comment]
АМД не поддерживает CUDA, можно запустить на процессоре.
[Rotor](https://github.com/phrutis/Rotor) OpenCL будет работать на GPU

**Comment by DapTice** [comment]
Настроил rotor, всё работает, но никак не могу подобрать grid size, rx 480 4g, после пары минут вырубается комп. Вопрос может не в тему, но какой лучше режим использовать если допустим хочу проверять всего один кошелёк? 

> АМД не поддерживает CUDA, можно запустить на процессоре. [Rotor](https://github.com/phrutis/Rotor) OpenCL будет работать на GPU

**Comment by phrutis** [comment]
Проверка-поиск идёт по базе. Могу ошибаться, но минимально в базе должно быть 1000 адресов.
Разницы в скорости что 1000, 1000000 адресов особой нет. Если вырубается комп, вероятней всего перегрев видюхи. Проверь охлаждение, температуру, переведи электропитание на мин. Это не хорошо, ищи на CPU.
