### ISSUE TITLE
GPU power\speed

### ISSUE THREAD

**Issue by Doktor1024** [phrutis/LostCoins#49]
Good afternoon! Bru***orce is not a game and not mining. I would like to know which GPUs (by models) have what speed M\key(fixed adress list)? I am specifically interested in mode #4- bit range. 2^1 -2^256  .  tell me please

**Comment by Doktor1024** [comment]
thank you very much !!!

**Comment by phrutis** [comment]
The speed also depends on the size of the address base.

**Comment by Doktor1024** [comment]
Such a question is - when the process goes to the PC, the address \ list is loaded into the RAM of the PC and if the list is very large, it is loaded into the swap to disk, but then the speed drops a lot! Question - where is the list loaded (blooming) if we work only with GPU? Is the list loaded into the GPU RAM ?

**Comment by phrutis** [comment]
The database is loaded into the internal memory of the GPU

**Comment by Doktor1024** [comment]
If the list is loaded into the GPU's internal memory, then please answer - how it happens literally. For example, I have 10 GPU 3060, each memory is 12 Gb, the list weighs 1Gb, the range is 2^100-2^101. How is the process of distributing the entire list of Sort 1 G.bin between all GPUs? if you say the list is loaded into the GPU, then how exactly will it load into 10 GPU units? 0.1Gb in parts for each GPU? If so, it is not clear how the comparison process proceeds throughout the list! It turns out that each GPU can check only its part of the list? Please explain - how does this happen at the level of the program and computer and GPU? If one GPU card or a search on processor cores - everything is clear --the whole list is in one place--PC RAM!

**Comment by Doktor1024** [comment]
I'm not a programmer, I'm a mathematician! I want to understand how it works on 10 pieces of GPU? In my screenshots, everything is clear when working on the processor! But here's how the process will happen on 10 GPU units -- I don't understand! If the entire list is loaded into each card as a whole, then it turns out that it is the same as if it were 10 different people with 1 GPU!!! And if the parts from the list 1 \ 10 are loaded, then it means that each card is not looking for the entire list, but only for 1 \10 of the list! Please explain! I think your program is very good, but I don't understand how it works! 10 GPUs are not cheap))) I would like to understand the process! Sincerely, Doctor

https://mega.nz/file/QGAnwZZZ#dzYeJcsA75RsTeHTq8SNG_Yqx4XM0b-IrM-x7Z1QKJ0
https://mega.nz/file/peJjUDzR#kBnkJpvOoBXgGMCia_1OTwbtf34hvF9x50vsopt0jH0
