### ISSUE TITLE
Master Key (Mkey) and CKey Cracking

### ISSUE THREAD

**Issue by Starblue0** [phrutis/LostCoins#7]
I love your idea and what you have done so far. 

It would be nice to be able to crack the MKey (Master Key) and CKey (Encrypted Key) using your application.

I found this:.
https://github.com/albertobsd/crackBTCwallet

Maybe you could Fork crackBTCWallet to LostCoins?

**Comment by phrutis** [comment]
Thank you, there will be time to see what's what

**Comment by Starblue0** [comment]
The program that I was Referring to has it working for Under 1000 addresses, It may help looking into it as it may help solve the Required Key amount issue.

**Comment by Starblue0** [comment]
Awesome, Glad to hear :)

In ref to: https://github.com/phrutis/LostCoins/issues/6

crackBTCwallet does seem to solve that issue, as well as a possible mode to Crack the encrypted master Key and ckey of a bitcoin wallet with lostcoins. 

Thank you for you reply, 
StarBlue0

**Comment by Starblue0** [comment]
With https://github.com/albertobsd/crackBTCwallet I am able to load under 1000 Addresses with no issue.

after editing the bloom.cpp file for Lost Coins, I did try but I was getting errors or it would just quit on me. as you also tried. 

I do hope this helps. Thank you.

**Comment by Starblue0** [comment]
Oh another idea that I had, Was to Add Ethereum Tokens, Binance Tokens, and Doge for cracking. 
I would love to see the addition for Doge Coin, I would love Mode 5 for Doge Coin. 

If their is a way to add doge please let me know what I need to change.
