### ISSUE TITLE
LostCoins.exe mode 1 doesn't support more than 2 GPU's.

### ISSUE THREAD

**Issue by marssystems** [phrutis/LostCoins#8]
LostCoins.exe mode 1 doesn't support more than 2 GPU's.

If I run -

LostCoins.exe -t 0 -g -i 0,1 -x 288,512 -f test.bin -r 1 -s ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f0000000 -z ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61ffffffff

it works fine - but if I run -

LostCoins.exe -t 0 -g -i 0,1,2 -x 288,512 -f test.bin -r 1 -s ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f0000000 -z ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61ffffffff

the program crashes.

**Comment by phrutis** [comment]
You are not connecting the GPU correctly.
The name of your GPUs cards? 
Example for 2 GPU 
```LostCoins.exe -t 0 -g -i 0,1 -x 288,512,288,512 -f test.bin -r 1 -s ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f0000000 -z ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61ffffffff```
If you do not know your Grid
```LostCoins.exe -t 0 -g -i 0,1 -f test.bin -r 1 -s ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f0000000 -z ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61ffffffff```
-i 0,1 or -i 1,2 It is necessary to indicate under which number the desired card

**Comment by marssystems** [comment]
I use Nvidia P106-90 cards.

If I leave out the -x parameter (--gpux 256,256,256,256), the grid is configured automatically for each of the first 2 GPU's but fails if I use 3 cards.

**Comment by phrutis** [comment]
Weak cards are better than automatic ones.  -i 0,1,2 for 3 GPUs
If it does not work, you can run 3 copies of the program

**Comment by marssystems** [comment]
If I run the program in mode 4 - it works fine -

LostCoins.exe -t 0 -g -i 0,1,2 -f test.bin -r 4 -s 64 -z 72

and configures the grid for all 3 GPUs automatically correctly.
So there must be a small programming error in the mode 1 code.

**Comment by phrutis** [comment]
In the example mode 1 I indicated, there is a small range. 
Try to specify a larger range for two cards

**Comment by marssystems** [comment]
There is no problem running 2 cards.

The program fails when I run it with 3 cards.

**Comment by phrutis** [comment]
Error 3 GPUa only in the mode 1 or in others modes?

**Comment by marssystems** [comment]
Just mode 1.

Mode 2 and mode 4 work fine.

**Comment by phrutis** [comment]
Completely remade mode 1, test on 2 gpu. (Download new LostCoins.exe)

**Comment by marssystems** [comment]
OK - I will test it with 3 GPUs shortly.
